query salesChannelCustom($bindingId: String!) {
  salesChannelCustom(bindingId: $bindingId)
    @context(provider: "vtex.currency-selector") {
    bindingId
    salesChannelInfo {
      salesChannel
      customLabel
    }
  }
}
