mutation updateCartSalesChannel($orderFormId: ID, $salesChannel: String) {
  updateSalesChannel(orderFormId: $orderFormId, salesChannel: $salesChannel)
    @context(provider: "vtex.binding-selector@1.x") {
    orderFormId
  }
}
