export const salesChannelList = [
  {
    Id: 1,
    Name: 'España B2C',
    IsActive: true,
    ProductClusterId: null,
    CountryCode: 'ESP',
    CultureInfo: 'es-ES',
    TimeZone: 'Romance Standard Time',
    CurrencyCode: 'EUR',
    CurrencySymbol: '€',
    CurrencyLocale: 1150,
    CurrencyFormatInfo: {
      CurrencyDecimalDigits: 2,
      CurrencyDecimalSeparator: ',',
      CurrencyGroupSeparator: ' ',
      CurrencyGroupSize: 3,
      StartsWithCurrencySymbol: false,
    },
    Origin: null,
    Position: 1,
    ConditionRule: null,
    CurrencyDecimalDigits: null,
  },
  {
    Id: 2,
    Name: 'B2B',
    IsActive: true,
    ProductClusterId: null,
    CountryCode: 'ESP',
    CultureInfo: 'es-ES',
    TimeZone: 'Romance Standard Time',
    CurrencyCode: 'EUR',
    CurrencySymbol: '€',
    CurrencyLocale: 1150,
    CurrencyFormatInfo: {
      CurrencyDecimalDigits: 2,
      CurrencyDecimalSeparator: ',',
      CurrencyGroupSeparator: ' ',
      CurrencyGroupSize: 3,
      StartsWithCurrencySymbol: false,
    },
    Origin: null,
    Position: 2,
    ConditionRule: 'approved=true',
    CurrencyDecimalDigits: null,
  },
  {
    Id: 3,
    Name: 'Global',
    IsActive: true,
    ProductClusterId: null,
    CountryCode: 'GBR',
    CultureInfo: 'en-GB',
    TimeZone: 'GMT Standard Time',
    CurrencyCode: 'EUR',
    CurrencySymbol: '€',
    CurrencyLocale: 1150,
    CurrencyFormatInfo: {
      CurrencyDecimalDigits: 2,
      CurrencyDecimalSeparator: ',',
      CurrencyGroupSeparator: ' ',
      CurrencyGroupSize: 3,
      StartsWithCurrencySymbol: false,
    },
    Origin: null,
    Position: 3,
    ConditionRule: null,
    CurrencyDecimalDigits: null,
  },
  {
    Id: 4,
    Name: 'South Africa',
    IsActive: true,
    ProductClusterId: null,
    CountryCode: 'ZAF',
    CultureInfo: 'af-ZA',
    TimeZone: 'Romance Standard Time',
    CurrencyCode: 'ZAR',
    CurrencySymbol: 'R',
    CurrencyLocale: 1078,
    CurrencyFormatInfo: {
      CurrencyDecimalDigits: 2,
      CurrencyDecimalSeparator: ',',
      CurrencyGroupSeparator: ' ',
      CurrencyGroupSize: 3,
      StartsWithCurrencySymbol: true,
    },
    Origin: null,
    Position: 4,
    ConditionRule: null,
    CurrencyDecimalDigits: null,
  },
  {
    Id: 5,
    Name: 'Portugal',
    IsActive: true,
    ProductClusterId: null,
    CountryCode: 'PRT',
    CultureInfo: 'pt-PT',
    TimeZone: 'GMT Standard Time',
    CurrencyCode: 'EUR',
    CurrencySymbol: '€',
    CurrencyLocale: 1150,
    CurrencyFormatInfo: {
      CurrencyDecimalDigits: 2,
      CurrencyDecimalSeparator: ',',
      CurrencyGroupSeparator: ' ',
      CurrencyGroupSize: 3,
      StartsWithCurrencySymbol: false,
    },
    Origin: null,
    Position: 5,
    ConditionRule: null,
    CurrencyDecimalDigits: null,
  },
  {
    Id: 6,
    Name: 'canarias',
    IsActive: true,
    ProductClusterId: null,
    CountryCode: 'ESP',
    CultureInfo: 'es-ES',
    TimeZone: 'Romance Standard Time',
    CurrencyCode: 'EUR',
    CurrencySymbol: '€',
    CurrencyLocale: 1150,
    CurrencyFormatInfo: {
      CurrencyDecimalDigits: 2,
      CurrencyDecimalSeparator: ',',
      CurrencyGroupSeparator: ' ',
      CurrencyGroupSize: 3,
      StartsWithCurrencySymbol: false,
    },
    Origin: null,
    Position: 6,
    ConditionRule: null,
    CurrencyDecimalDigits: null,
  },
  {
    Id: 7,
    Name: 'Backup 1',
    IsActive: false,
    ProductClusterId: null,
    CountryCode: 'BRA',
    CultureInfo: 'pt-BR',
    TimeZone: 'E. South America Standard Time',
    CurrencyCode: 'BRL',
    CurrencySymbol: 'R$',
    CurrencyLocale: 1046,
    CurrencyFormatInfo: {
      CurrencyDecimalDigits: 2,
      CurrencyDecimalSeparator: ',',
      CurrencyGroupSeparator: '.',
      CurrencyGroupSize: 3,
      StartsWithCurrencySymbol: true,
    },
    Origin: null,
    Position: 7,
    ConditionRule: null,
    CurrencyDecimalDigits: null,
  },
  {
    Id: 8,
    Name: 'Backup 2',
    IsActive: false,
    ProductClusterId: null,
    CountryCode: 'ESP',
    CultureInfo: 'ca-ES',
    TimeZone: 'Romance Standard Time',
    CurrencyCode: 'EUR',
    CurrencySymbol: '€',
    CurrencyLocale: 1150,
    CurrencyFormatInfo: {
      CurrencyDecimalDigits: 2,
      CurrencyDecimalSeparator: ',',
      CurrencyGroupSeparator: ' ',
      CurrencyGroupSize: 3,
      StartsWithCurrencySymbol: false,
    },
    Origin: null,
    Position: 8,
    ConditionRule: null,
    CurrencyDecimalDigits: null,
  },
]
