export const tenantInfo = {
  slug: 'powerplanet',
  title: 'powerplanet',
  edition: 'vtex:tier-1339',
  infra: 'VTEX',
  bindings: [
    {
      id: '53b76989-6cd8-4d41-8faf-b3f6abe0b334',
      canonicalBaseAddress: 'powerplanet.myvtex.com/admin',
      alternateBaseAddresses: [],
      defaultLocale: 'en-GB',
      supportedLocales: ['es-AR', 'pt-BR', 'en-US'],
      defaultCurrency: 'EUR',
      supportedCurrencies: ['EUR'],
      extraContext: {},
      targetProduct: 'vtex-admin',
    },
    {
      id: '7cf38d3b-efa0-4d47-8201-d8b58cd4d3fd',
      canonicalBaseAddress: 'www.we-demostore.com/pt',
      alternateBaseAddresses: [
        'powerplanet.myvtex.com/pt',
        'b2c.powerplanet.com/pt',
      ],
      defaultLocale: 'pt-PT',
      supportedLocales: ['es-ES', 'pt-PT', 'en-GB', 'fr-FR'],
      defaultCurrency: 'EUR',
      supportedCurrencies: ['EUR'],
      extraContext: { portal: { salesChannel: 5 } },
      targetProduct: 'vtex-storefront',
    },
    {
      id: 'e84d830f-8e31-4b38-97e4-87e2c3801929',
      canonicalBaseAddress: 'www.we-demostore.com/fr',
      alternateBaseAddresses: [
        'powerplanet.myvtex.com/fr',
        'b2c.powerplanet.com/fr',
      ],
      defaultLocale: 'fr-FR',
      supportedLocales: ['es-ES', 'pt-PT', 'en-GB', 'fr-FR'],
      defaultCurrency: 'ZAR',
      supportedCurrencies: ['ZAR'],
      extraContext: { portal: { salesChannel: 4 } },
      targetProduct: 'vtex-storefront',
    },
    {
      id: 'bb2b7747-30d9-466e-9abe-2f90caf7150f',
      canonicalBaseAddress: 'www.we-demostore.com/en',
      alternateBaseAddresses: [
        'powerplanet.myvtex.com/en',
        'b2c.powerplanet.com/en',
      ],
      defaultLocale: 'en-GB',
      supportedLocales: ['es-ES', 'pt-PT', 'en-GB', 'fr-FR'],
      defaultCurrency: 'EUR',
      supportedCurrencies: ['EUR'],
      extraContext: { portal: { salesChannel: 3 } },
      targetProduct: 'vtex-storefront',
    },
    {
      id: 'ff7344d2-60fa-4aaa-b342-07d768adfbb9',
      canonicalBaseAddress: 'b2b.powerplanet.com/',
      alternateBaseAddresses: [],
      defaultLocale: 'es-ES',
      supportedLocales: ['es-ES', 'pt-PT', 'en-GB', 'fr-FR'],
      defaultCurrency: 'EUR',
      supportedCurrencies: ['EUR'],
      extraContext: { portal: { salesChannel: 2 } },
      targetProduct: 'vtex-storefront',
    },
    {
      id: 'a9c6542d-f8a6-4f80-9465-e2de705d5e27',
      canonicalBaseAddress: 'www.we-demostore.com/es',
      alternateBaseAddresses: [
        'powerplanet.myvtex.com/es',
        'powerplanet.myvtex.com/',
        'b2c.powerplanet.com/',
        'www.we-demostore.com/',
        'b2c.powerplanet.com/es',
      ],
      defaultLocale: 'es-ES',
      supportedLocales: ['es-ES', 'pt-PT', 'en-GB', 'fr-FR'],
      defaultCurrency: 'EUR',
      supportedCurrencies: ['EUR'],
      extraContext: { portal: { salesChannel: 1 } },
      targetProduct: 'vtex-storefront',
    },
  ],
  defaultCurrency: 'EUR',
  defaultLocale: 'es-ES',
}
