mutation updateSalesChannelCustom(
  $bindingId: String!
  $salesChannelInfo: [SalesChannelCustomInfo]!
) {
  updateSalesChannelCustom(
    bindingId: $bindingId
    salesChannelInfo: $salesChannelInfo
  ) @context(provider: "vtex.currency-selector") {
    bindingId
    salesChannelInfo {
      customLabel
      salesChannel
    }
  }
}
